export const articlesArray = [
  {
    imgMain: 'man-walking.svg',
    imgMainAlt: 'Man walking',
    category: 'Category',
    data: 'November 22, 2021',
    text: 'Pitch termsheet backing validation focus release.',
    author: 'Chandler Bing',
    profileImg: 'avatar-Chandler.svg',
    profileImgAlt: "Chandler's avatar",
  },
  {
    imgMain: 'woman-speaking.svg',
    imgMainAlt: 'Woman speaking',
    category: 'Category',
    data: 'November 22, 2021',
    text: 'Seed round direct mailing non-disclosure agreement graphical user interface rockstar.',
    author: 'Rachel Green',
    profileImg: 'avatar-Rachel.svg',
    profileImgAlt: "Rachel's avatar",
  },
  {
    imgMain: 'man-with-docs.svg',
    imgMainAlt: 'Man with documents',
    category: 'Category',
    data: 'November 22, 2021',
    text: 'Beta prototype sales iPad gen-z marketing network effects value proposition',
    author: 'Monica Geller',
    profileImg: 'avatar-Monica.svg',
    profileImgAlt: "Monica's avatar",
  },
  {
    imgMain: 'man-speaking.svg',
    imgMainAlt: 'Man speaking',
    category: 'Category',
    data: 'November 22, 2021',
    text: 'Pitch termsheet backing validation focus release.',
    author: 'Chandler Bing',
    profileImg: 'avatar-Chandler.svg',
    profileImgAlt: "Chandler's avatar",
  },
  {
    imgMain: 'office.svg',
    imgMainAlt: 'Office',
    category: 'Category',
    data: 'November 22, 2021',
    text: 'Seed round direct mailing non-disclosure agreement graphical user interface rockstar.',
    author: 'Rachel Green',
    profileImg: 'avatar-Rachel.svg',
    profileImgAlt: "Rachel's avatar",
  },
  {
    imgMain: 'deal.svg',
    imgMainAlt: 'Deal',
    category: 'Category',
    data: 'November 22, 2021',
    text: 'Beta prototype sales iPad gen-z marketing network effects value proposition',
    author: 'Monica Geller',
    profileImg: 'avatar-Monica.svg',
    profileImgAlt: "Monica's avatar",
  },
];
